<?xml version="1.0"?>

<robot name="moto" xmlns:xacro="http://ros.org/wiki/xacro">

<!--    Properties    -->
<!-- <xacro:property name="namespace" value="moto"/> -->
<xacro:property name="PI" value="3.1415926535897931"/>
<xacro:property name="h" value=".05"/>
<xacro:property name="height" value=".2"/>
<xacro:property name="width" value="1"/>
<xacro:property name="length" value="2"/>
<xacro:property name="radius" value=".3"/>
<xacro:property name="mass_base" value="0.5"/>
<xacro:property name="mass_wheel" value="0.2"/>
<xacro:property name="mass_gyro" value="1"/>

    <!-- Macro for the inertial properties -->


  <!-- Used for fixing robot to Gazebo 'base_link' -->



    <link name="base_link">
    <collision>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
	        <box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
	    <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <mass value="${mass_base}"/>
      <inertia
	  ixx="${mass_base/ 12.0 * (height*height + width*width)}" ixy="0.0" ixz="0.0"
	  iyy="${mass_base / 12.0 * (height*height + length*length)}" iyz="0.0"
	  izz="${mass_base / 12.0 * (length*length + width*width)}"/>
    </inertial> 
  </link>

 <joint name="front_wheel_joint" type="continuous">
        <origin xyz="${length/2} 0.0 ${height/2}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="front_wheel"/>
        <axis xyz="0 1 0"/>
        <!-- <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/> -->
    </joint>


    <joint name="back_wheel_joint" type="continuous">
        <origin xyz="${-length/2} 0.0 ${height/2}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="back_wheel"/>
        <axis xyz="0 1 0"/>
        <!-- <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/> -->
    </joint>

    <link name="front_wheel">
        <visual>
        <origin xyz="0.0 0.0 0.0" rpy="${PI/2} 0.0 0.0"/> 
        <geometry>
            <cylinder radius="${radius}" length="${h}"/>
            <!-- <mesh filename="${mesh_base}" scale="1.0"/> -->
        </geometry>  
        </visual>
        <collision>
        <origin xyz="0.0 0.0 0.0" rpy="${PI/2} 0.0 0.0"/> 
            <geometry>
                <cylinder radius="${radius}" length="${h}"/>
                <!-- <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/> -->
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="${PI/2} 0.0 0.0"/>
            <mass value="${mass_wheel}"/>
            <inertia
            ixx="${mass_wheel / 12.0 * (3*radius*radius + h*h)}" ixy="0.0" ixz="0.0"
            iyy="${mass_wheel / 12.0 * (3*radius*radius + h*h)}" iyz="0.0"
            izz="${mass_wheel / 2.0 * (radius*radius)}"/> 
        </inertial>
    </link>

    <link name="back_wheel">

        <visual>
        <origin xyz="0.0 0.0 0.0" rpy="${PI/2} 0.0 0.0"/> 
        <geometry>
            <cylinder radius="${radius}" length="${h}"/>
            <!-- <mesh filename="${mesh_base}" scale="1.0"/> -->
        </geometry>  
        </visual>

        <collision>
        <origin xyz="0.0 0.0 0.0" rpy="${PI/2} 0.0 0.0"/> 
            <geometry>
                <cylinder radius="${radius}" length="${h}"/>
                <!-- <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/> -->
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="${PI/2} 0.0 0.0"/>
            <mass value="${mass_wheel}"/>
            <inertia
            ixx="${mass_wheel / 12.0 * (3*radius*radius + h*h)}" ixy="0.0" ixz="0.0"
            iyy="${mass_wheel / 12.0 * (3*radius*radius + h*h)}" iyz="0.0"
            izz="${mass_wheel / 2.0 * (radius*radius)}"/> 
        </inertial>
        
    </link>
</robot>
       