moto:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  gyro_angle:
    type: effort_controllers/JointPositionController
    joint: gyro_support_joint
    pid: {p: 30.0, i: 1.0, d: 0.50}

  gyro_velocity:
    type: effort_controllers/JointVelocityController
    joint: gyro_joint
    pid: {p: 50.0, i: 2.0, d: .10}

