moto:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  gyro_angle:
    type: effort_controllers/JointPositionController
    joint: gyro_support_joint
    pid: {p: 1000.0, i: 100.0, d: 50.0}

  gyro_velocity:
    type: effort_controllers/JointVelocityController
    joint: gyro_joint
    pid: {p: 500.0, i: 50.0, d: 10.0}

